### ISSUE TITLE
Project Design Review

### ISSUE THREAD

**Issue by jkruser86** [ssoperMadisonCollege/ChoreTracker#1]
# Design/Code Review 1

### Reviewer: Jamie Kruser

|Item |Criteria|Rating | Comments/Suggestions|
|--------|---------|---------------|---|
||| Use the following scale:<br> 1= It needs more work<br>  2 = Somewhat<br> 3 = Yes it is great|Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| 3| Great problem statement that was filled out pretty thoroughly. Could describe in more detail how the site will be setup. Also, maybe explain what a kanban board is a bit while also still including the wikipedia link.
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | 2| As we discussed, this was something that was put off a bit in order to make better use of Sam's time. The screenshots that he has are useful and well done. I think to better fit on a mobile device, some of the task layouts will have to be moved to a separate section. Also, having the tracker go out longer than originally thought will make this accessible to people that want just long term reminders, like having vents cleaned yearly, etc.
|**Data model**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| 1| Sam didn't have this section done but he described it to me and he seems to have a grasp of what he wants to do. I think his plan will work but mentioned the possibility of having a friends list so you could keep all the people you create tasks for easily accessible.
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages.| 2| Sam has a grasp of where he wants his code to go and has a great plan for what products he wants to use. I think getting most of the jsps working is a great place to start. Also, I mentioned to Sam that using Servlets may be the best way to move between links.

**Comment by ssoperMadisonCollege** [comment]
@jkruser86 - Thanks again for the feedback - I have now implemented all the changes you suggested in your code review.  The work is not perfect, but further iterations are coming!
