### ISSUE TITLE
Design Code Review

### ISSUE THREAD

**Issue by brookeswanson** [ssoperMadisonCollege/ChoreTracker#2]
# Design/Code Review 1

### Reviewer: Brooke Swanson

|Item |Criteria|Rating | Comments/Suggestions|
|--------|---------|---------------|---|
||| Use the following scale:<br> 1= It needs more work<br>  2 = Somewhat<br> 3 = Yes it is great|Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| 3 | You do a good job of explaining the problem. The link to the kanban wiki was a good choice. I would recommend that you expand on the solution. Additionally it is unclear if this is a mobile application, or a web application.|
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | 1 | It seems like you have a good idea of where you're going. I like the simple clean design of the log in screen.  The application flow is currently unclear, but I believe we talked about you losing data.  I'm still unclear how often you will be sending notifications to the end users. |
|**Data model**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| 2 | This diagram is representing more than it should be. It looks like it is both an ERD and UML, where it represents the relationships, but also has the methods. I am unsure of the UserHouseChore relationship. I would be interested to hear why this might be necessary. It seems redundant, since you already have an assigned user, you could maybe just have a HouseChore relationship since there is an already associated User.|
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages. | 2 | The gitignore is included and implemented. The user class is appropriately sized. I would recommend adding a constructor with all the instance variables for your user class. It will clean up the code in your user Dao test.  Overall great job so far! |

**Comment by ssoperMadisonCollege** [comment]
@bswanson3 Thanks for the feedback! I implemented all the changes you suggested.  

RE: the combination UML/ERD - I just liked having this combined into one diagram.  The ideas for the methods kept cropping up in my head so I just added them in.

RE: the UserHouseChore relationship - I think I see what you're saying, I updated the database diagram to reflect a less redundant relationship.
